name: Trigger External Build

on:
  push:
    branches:
      - main
      - master

jobs:
  webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Send POST request to build server
        run: |
          REPO_URL="${{ github.repository_url }}"
          echo "Sending repo: $REPO_URL"   # 方便排查
          curl -X POST http://coldmouse.net:15379/build \
            -H "Content-Type: application/json" \
            -d "{\"repo\": \"$REPO_URL\"}"
